# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Emerald City Investment Club
email: ecic@emeraldcityinvestmentclub.org
description: > # this means to ignore newlines until "baseurl:"
  A Seattle-based member of <a href="https://www.betterinvesting.org">NAIC</a>.<br>
  Making long-term stock investments since 1987.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emeraldcityinvestmentclub.org" # the base hostname & protocol for your site
twitter_username: ecicinvest
github_username:  ecicinvest

# Build settings
markdown: kramdown
